### ISSUE TITLE
Verifying token signature

### ISSUE THREAD

**Issue by Obyka** [IT-Habich/SocialiteAdfsProvider#2]
Hi,
As I understand, you don't verify the token signature when parsing the token.
```php
    protected function getUserByToken($token)
    {
        return json_decode(base64_decode(explode('.', $token)[1]), true);
    }
```
I suggest a workflow similar to that one: https://github.com/rinkp/socialite-azureb2c/blob/426cf31268405e437b07e7bafbb674a7ac6fb28e/Provider.php

It uses the .well-known/ endpoint to gather the current key.
Supporting signature verification would be nice since it provides authenticity and data integrity.

**Comment by CodeAdminDe** [comment]
@Obyka thanks for opening the issue. Sorry for the delay. 

Yes, you are right, of course. The first implementation was the simplest and fastest "basic" one. Based on the link you shared, It seems very straight forward to implement it. I'll release the new version soon - then also with signature validation. :-)
